# Numpy tutorial

## Preliminaries


This command is for importing the numpy module in your python scripts:
```bash
pip install numpy
```

You can use functions in numpy via `np.XX` (e.g. `np.array`)

You can replace it with:

- import numpy as (anything word you like)

- from numpy import numpy (danger! This may cause conflicts in different functions. I don't recommend for this way of importing numpy)


In [2]:
# make sure you have installed numpy via:
# pip install numpy

import numpy as np

## Creating arrays and matrix

You can create **arrays** in `numpy` of different dimensions, which is one of the most frequently used commands in numpy.

- Creating arrays manually

    You can create arrays manually by **writing all elements into the arrays**.



In [2]:
# Creating arrays manually

# One dimension (like a vector storing int value)
array_1d = np.array([1,2,3,4])

# Two dimensions (4*4)
array_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,1,4,16]])

# Three dimensions (more complex)
array_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

# Visualize
print(f"Showing arrays of one-dimension: \n",array_1d)
print(f"Showing arrays of two-dimensions: \n",array_2d)
print(f"Showing arrays of three-dimensions: \n",array_3d)


Showing arrays of one-dimension: 
 [1 2 3 4]
Showing arrays of two-dimensions: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13  1  4 16]]
Showing arrays of three-dimensions: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


- Creating several **templates**

    It's time-consuming to write all elements in your python scripts if the size or the dimensions of arrays becomes very large. (More bigger the dimension is, there are more square backets!)

    Thus, you can use the templates in `numpy` to initilize an array automatically.

In [ ]:
# Creating several templates

# If all elements of the matrix is of the same initial value:

# For zero-matrix
zero_int_matrix = np.zeros((5,5), dtype = 'int64')
zero_double_matrix = np.zeros((4,5), dtype = 'float64')
zero_int_bigger_matrix = np.zeros((2,2,2))

print(zero_int_matrix)
print(zero_double_matrix)
print(zero_int_bigger_matrix)


[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [7]:
# Filled with a specific number
tobefilled = 64

filled_array = np.full((3,4), fill_value= tobefilled, dtype = 'int64')
print(filled_array)


[[64 64 64 64]
 [64 64 64 64]
 [64 64 64 64]]
